version: '2'
services:
    nginx:
        image: nginx
        container_name: nginx
        hostname: nginx
        environment:
             - PS1="`whoami`@`hostname`:`pwd`# "
        #expose:
        links:
            - node1:node1
            - node2:node2
            - node3:node3
        ports: 
            - "80:80"
        working_dir: /
    node1:
        build: ./node
        container_name: node1
        hostname: node1
        environment:
             - PS1="`whoami`@`hostname`:`pwd`# "
        #expose:
        links:
            - redis:redis
        ports: 
            - "8080"
    node2:
        build: ./node
        container_name: node2
        hostname: node2
        environment:
             - PS1="`whoami`@`hostname`:`pwd`# "
        #expose:
        links:
            - redis:redis
        ports: 
            - "8080"
    node3:
        build: ./node
        container_name: node3
        hostname: node3
        environment:
             - PS1="`whoami`@`hostname`:`pwd`# "
        #expose:
        links:
            - redis:redis
        ports: 
            - "8080"
    redis:
        build: ./redis
        container_name: redis
        hostname: redis
        environment:
             - PS1="`whoami`@`hostname`:`pwd`# "
        #expose:
        links:
            - redis:redis
        ports: 
            - "6379"

    
        
    
