VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.box = "blinkreaction/boot2docker"

	config.vm.box_version = "1.9.0"
	config.vm.provider :virtualbox do |vb|
	  vb.name = "docker_demo"
	end
	#Vagrant -> Docker Synced Folders
	
	#Vagrant Provisioning
	config.vm.provision :docker

	#Vagrant Provisioning Plugin
	#config.vm.provision :docker_compose, yml: "/vagrant/compose.yaml", run: "always"
	
	#VM Network Configurations
	
	#Aplications Foward Ports
	#VM Network Configurations
	config.vm.network :forwarded_port, guest: 80, host: 80
end